#!/usr/bin/gawk -f
# CS152 Lab 3

BEGIN {
	RS = ""
	ORS = ""
	limit = 256
}

{
	gsub(/[^[:xdigit:]]/, "")
	n = length($0)
	for (i = 1; i < n; i += 2) {
		if (i > limit) {
			break
		}
		if ((i % 16) == 1) {
			print "\n  .byte"
		} else {
			print ","
		}
		x = substr($0, i, 2)
		print " 0x" x
	}
	print "\n"
	exit
}
